paraBirimleri = [
{"name": "Andorran Peseta", "symbol": "ADP"},
{"name": "United Arab Emirates Dirham", "symbol": "AED"},
{"name": "Afghan Afghani (1927–2002)", "symbol": "AFA"},
{"name": "Afghan Afghani", "symbol": "AFN"},
{"name": "Albanian Lek (1946–1965)", "symbol": "ALK"},
{"name": "Albanian Lek", "symbol": "ALL"},
{"name": "Armenian Dram", "symbol": "AMD"},
{"name": "Netherlands Antillean Guilder", "symbol": "ANG"},
{"name": "Angolan Kwanza", "symbol": "AOA"},
{"name": "Angolan Kwanza (1977–1991)", "symbol": "AOK"},
{"name": "Angolan New Kwanza (1990–2000)", "symbol": "AON"},
{"name": "Angolan Readjusted Kwanza (1995–1999)", "symbol": "AOR"},
{"name": "Argentine Austral", "symbol": "ARA"},
{"name": "Argentine Peso Ley (1970–1983)", "symbol": "ARL"},
{"name": "Argentine Peso (1881–1970)", "symbol": "ARM"},
{"name": "Argentine Peso (1983–1985)", "symbol": "ARP"},
{"name": "Argentine Peso", "symbol": "ARS"},
{"name": "Austrian Schilling", "symbol": "ATS"},
{"name": "Australian Dollar", "symbol": "A$"},
{"name": "Aruban Florin", "symbol": "AWG"},
{"name": "Azerbaijani Manat (1993–2006)", "symbol": "AZM"},
{"name": "Azerbaijani Manat", "symbol": "AZN"},
{"name": "Bosnia-Herzegovina Dinar (1992–1994)", "symbol": "BAD"},
{"name": "Bosnia-Herzegovina Convertible Mark", "symbol": "BAM"},
{"name": "Bosnia-Herzegovina New Dinar (1994–1997)", "symbol": "BAN"},
{"name": "Barbadian Dollar", "symbol": "BBD"},
{"name": "Bangladeshi Taka", "symbol": "BDT"},
{"name": "Belgian Franc (convertible)", "symbol": "BEC"},
{"name": "Belgian Franc", "symbol": "BEF"},
{"name": "Belgian Franc (financial)", "symbol": "BEL"},
{"name": "Bulgarian Hard Lev", "symbol": "BGL"},
{"name": "Bulgarian Socialist Lev", "symbol": "BGM"},
{"name": "Bulgarian Lev", "symbol": "BGN"},
{"name": "Bulgarian Lev (1879–1952)", "symbol": "BGO"},
{"name": "Bahraini Dinar", "symbol": "BHD"},
{"name": "Burundian Franc", "symbol": "BIF"},
{"name": "Bermudan Dollar", "symbol": "BMD"},
{"name": "Brunei Dollar", "symbol": "BND"},
{"name": "Bolivian Boliviano", "symbol": "BOB"},
{"name": "Bolivian Boliviano (1863–1963)", "symbol": "BOL"},
{"name": "Bolivian Peso", "symbol": "BOP"},
{"name": "Bolivian Mvdol", "symbol": "BOV"},
{"name": "Brazilian New Cruzeiro (1967–1986)", "symbol": "BRB"},
{"name": "Brazilian Cruzado (1986–1989)", "symbol": "BRC"},
{"name": "Brazilian Cruzeiro (1990–1993)", "symbol": "BRE"},
{"name": "Brazilian Real", "symbol": "R$"},
{"name": "Brazilian New Cruzado (1989–1990)", "symbol": "BRN"},
{"name": "Brazilian Cruzeiro (1993–1994)", "symbol": "BRR"},
{"name": "Brazilian Cruzeiro (1942–1967)", "symbol": "BRZ"},
{"name": "Bahamian Dollar", "symbol": "BSD"},
{"name": "Bhutanese Ngultrum", "symbol": "BTN"},
{"name": "Burmese Kyat", "symbol": "BUK"},
{"name": "Botswanan Pula", "symbol": "BWP"},
{"name": "Belarusian New Ruble (1994–1999)", "symbol": "BYB"},
{"name": "Belarusian Ruble", "symbol": "BYR"},
{"name": "Belize Dollar", "symbol": "BZD"},
{"name": "Canadian Dollar", "symbol": "CA$"},
{"name": "Congolese Franc", "symbol": "CDF"},
{"name": "WIR Euro", "symbol": "CHE"},
{"name": "Swiss Franc", "symbol": "CHF"},
{"name": "WIR Franc", "symbol": "CHW"},
{"name": "Chilean Escudo", "symbol": "CLE"},
{"name": "Chilean Unit of Account (UF)", "symbol": "CLF"},
{"name": "Chilean Peso", "symbol": "CLP"},
{"name": "Chinese People’s Bank Dollar", "symbol": "CNX"},
{"name": "Chinese Yuan", "symbol": "CN¥"},
{"name": "Colombian Peso", "symbol": "COP"},
{"name": "Colombian Real Value Unit", "symbol": "COU"},
{"name": "Costa Rican Colón", "symbol": "CRC"},
{"name": "Serbian Dinar (2002–2006)", "symbol": "CSD"},
{"name": "Czechoslovak Hard Koruna", "symbol": "CSK"},
{"name": "Cuban Convertible Peso", "symbol": "CUC"},
{"name": "Cuban Peso", "symbol": "CUP"},
{"name": "Cape Verdean Escudo", "symbol": "CVE"},
{"name": "Cypriot Pound", "symbol": "CYP"},
{"name": "Czech Republic Koruna", "symbol": "CZK"},
{"name": "East German Mark", "symbol": "DDM"},
{"name": "German Mark", "symbol": "DEM"},
{"name": "Djiboutian Franc", "symbol": "DJF"},
{"name": "Danish Krone", "symbol": "DKK"},
{"name": "Dominican Peso", "symbol": "DOP"},
{"name": "Algerian Dinar", "symbol": "DZD"},
{"name": "Ecuadorian Sucre", "symbol": "ECS"},
{"name": "Ecuadorian Unit of Constant Value", "symbol": "ECV"},
{"name": "Estonian Kroon", "symbol": "EEK"},
{"name": "Egyptian Pound", "symbol": "EGP"},
{"name": "Eritrean Nakfa", "symbol": "ERN"},
{"name": "Spanish Peseta (A account)", "symbol": "ESA"},
{"name": "Spanish Peseta (convertible account)", "symbol": "ESB"},
{"name": "Spanish Peseta", "symbol": "ESP"},
{"name": "Ethiopian Birr", "symbol": "ETB"},
{"name": "Euro", "symbol": "€"},
{"name": "Finnish Markka", "symbol": "FIM"},
{"name": "Fijian Dollar", "symbol": "FJD"},
{"name": "Falkland Islands Pound", "symbol": "FKP"},
{"name": "French Franc", "symbol": "FRF"},
{"name": "British Pound Sterling", "symbol": "EUR"},
{"name": "Georgian Kupon Larit", "symbol": "GEK"},
{"name": "Georgian Lari", "symbol": "GEL"},
{"name": "Ghanaian Cedi (1979–2007)", "symbol": "GHC"},
{"name": "Ghanaian Cedi", "symbol": "GHS"},
{"name": "Gibraltar Pound", "symbol": "GIP"},
{"name": "Gambian Dalasi", "symbol": "GMD"},
{"name": "Guinean Franc", "symbol": "GNF"},
{"name": "Guinean Syli", "symbol": "GNS"},
{"name": "Equatorial Guinean Ekwele", "symbol": "GQE"},
{"name": "Greek Drachma", "symbol": "GRD"},
{"name": "Guatemalan Quetzal", "symbol": "GTQ"},
{"name": "Portuguese Guinea Escudo", "symbol": "GWE"},
{"name": "Guinea-Bissau Peso", "symbol": "GWP"},
{"name": "Guyanaese Dollar", "symbol": "GYD"},
{"name": "Hong Kong Dollar", "symbol": "HK$"},
{"name": "Honduran Lempira", "symbol": "HNL"},
{"name": "Croatian Dinar", "symbol": "HRD"},
{"name": "Croatian Kuna", "symbol": "HRK"},
{"name": "Haitian Gourde", "symbol": "HTG"},
{"name": "Hungarian Forint", "symbol": "HUF"},
{"name": "Indonesian Rupiah", "symbol": "IDR"},
{"name": "Irish Pound", "symbol": "IEP"},
{"name": "Israeli Pound", "symbol": "ILP"},
{"name": "Israeli Sheqel (1980–1985)", "symbol": "ILR"},
{"name": "Israeli New Sheqel", "symbol": "₪"},
{"name": "Indian Rupee", "symbol": "₹"},
{"name": "Iraqi Dinar", "symbol": "IQD"},
{"name": "Iranian Rial", "symbol": "IRR"},
{"name": "Icelandic Króna (1918–1981)", "symbol": "ISJ"},
{"name": "Icelandic Króna", "symbol": "ISK"},
{"name": "Italian Lira", "symbol": "ITL"},
{"name": "Jamaican Dollar", "symbol": "JMD"},
{"name": "Jordanian Dinar", "symbol": "JOD"},
{"name": "Japanese Yen", "symbol": "¥"},
{"name": "Kenyan Shilling", "symbol": "KES"},
{"name": "Kyrgystani Som", "symbol": "KGS"},
{"name": "Cambodian Riel", "symbol": "KHR"},
{"name": "Comorian Franc", "symbol": "KMF"},
{"name": "North Korean Won", "symbol": "KPW"},
{"name": "South Korean Hwan (1953–1962)", "symbol": "KRH"},
{"name": "South Korean Won (1945–1953)", "symbol": "KRO"},
{"name": "South Korean Won", "symbol": "₩"},
{"name": "Kuwaiti Dinar", "symbol": "KWD"},
{"name": "Cayman Islands Dollar", "symbol": "KYD"},
{"name": "Kazakhstani Tenge", "symbol": "KZT"},
{"name": "Laotian Kip", "symbol": "LAK"},
{"name": "Lebanese Pound", "symbol": "LBP"},
{"name": "Sri Lankan Rupee", "symbol": "LKR"},
{"name": "Liberian Dollar", "symbol": "LRD"},
{"name": "Lesotho Loti", "symbol": "LSL"},
{"name": "Lithuanian Litas", "symbol": "LTL"},
{"name": "Lithuanian Talonas", "symbol": "LTT"},
{"name": "Luxembourgian Convertible Franc", "symbol": "LUC"},
{"name": "Luxembourgian Franc", "symbol": "LUF"},
{"name": "Luxembourg Financial Franc", "symbol": "LUL"},
{"name": "Latvian Lats", "symbol": "LVL"},
{"name": "Latvian Ruble", "symbol": "LVR"},
{"name": "Libyan Dinar", "symbol": "LYD"},
{"name": "Moroccan Dirham", "symbol": "MAD"},
{"name": "Moroccan Franc", "symbol": "MAF"},
{"name": "Monegasque Franc", "symbol": "MCF"},
{"name": "Moldovan Cupon", "symbol": "MDC"},
{"name": "Moldovan Leu", "symbol": "MDL"},
{"name": "Malagasy Ariary", "symbol": "MGA"},
{"name": "Malagasy Franc", "symbol": "MGF"},
{"name": "Macedonian Denar", "symbol": "MKD"},
{"name": "Macedonian Denar (1992–1993)", "symbol": "MKN"},
{"name": "Malian Franc", "symbol": "MLF"},
{"name": "Myanmar Kyat", "symbol": "MMK"},
{"name": "Mongolian Tugrik", "symbol": "MNT"},
{"name": "Macanese Pataca", "symbol": "MOP"},
{"name": "Mauritanian Ouguiya", "symbol": "MRO"},
{"name": "Maltese Lira", "symbol": "MTL"},
{"name": "Maltese Pound", "symbol": "MTP"},
{"name": "Mauritian Rupee", "symbol": "MUR"},
{"name": "Maldivian Rupee (1947–1981)", "symbol": "MVP"},
{"name": "Maldivian Rufiyaa", "symbol": "MVR"},
{"name": "Malawian Kwacha", "symbol": "MWK"},
{"name": "Mexican Peso", "symbol": "MX$"},
{"name": "Mexican Silver Peso (1861–1992)", "symbol": "MXP"},
{"name": "Mexican Investment Unit", "symbol": "MXV"},
{"name": "Malaysian Ringgit", "symbol": "MYR"},
{"name": "Mozambican Escudo", "symbol": "MZE"},
{"name": "Mozambican Metical (1980–2006)", "symbol": "MZM"},
{"name": "Mozambican Metical", "symbol": "MZN"},
{"name": "Namibian Dollar", "symbol": "NAD"},
{"name": "Nigerian Naira", "symbol": "NGN"},
{"name": "Nicaraguan Córdoba (1988–1991)", "symbol": "NIC"},
{"name": "Nicaraguan Córdoba", "symbol": "NIO"},
{"name": "Dutch Guilder", "symbol": "NLG"},
{"name": "Norwegian Krone", "symbol": "NOK"},
{"name": "Nepalese Rupee", "symbol": "NPR"},
{"name": "New Zealand Dollar", "symbol": "NZ$"},
{"name": "Omani Rial", "symbol": "OMR"},
{"name": "Panamanian Balboa", "symbol": "PAB"},
{"name": "Peruvian Inti", "symbol": "PEI"},
{"name": "Peruvian Nuevo Sol", "symbol": "PEN"},
{"name": "Peruvian Sol (1863–1965)", "symbol": "PES"},
{"name": "Papua New Guinean Kina", "symbol": "PGK"},
{"name": "Philippine Peso", "symbol": "PHP"},
{"name": "Pakistani Rupee", "symbol": "PKR"},
{"name": "Polish Zloty", "symbol": "PLN"},
{"name": "Polish Zloty (1950–1995)", "symbol": "PLZ"},
{"name": "Portuguese Escudo", "symbol": "PTE"},
{"name": "Paraguayan Guarani", "symbol": "PYG"},
{"name": "Qatari Rial", "symbol": "QAR"},
{"name": "Rhodesian Dollar", "symbol": "RHD"},
{"name": "Romanian Leu (1952–2006)", "symbol": "ROL"},
{"name": "Romanian Leu", "symbol": "RON"},
{"name": "Serbian Dinar", "symbol": "RSD"},
{"name": "Russian Ruble", "symbol": "RUB"},
{"name": "Russian Ruble (1991–1998)", "symbol": "RUR"},
{"name": "Rwandan Franc", "symbol": "RWF"},
{"name": "Saudi Riyal", "symbol": "SAR"},
{"name": "Solomon Islands Dollar", "symbol": "SBD"},
{"name": "Seychellois Rupee", "symbol": "SCR"},
{"name": "Sudanese Dinar (1992–2007)", "symbol": "SDD"},
{"name": "Sudanese Pound", "symbol": "SDG"},
{"name": "Sudanese Pound (1957–1998)", "symbol": "SDP"},
{"name": "Swedish Krona", "symbol": "SEK"},
{"name": "Singapore Dollar", "symbol": "SGD"},
{"name": "St. Helena Pound", "symbol": "SHP"},
{"name": "Slovenian Tolar", "symbol": "SIT"},
{"name": "Slovak Koruna", "symbol": "SKK"},
{"name": "Sierra Leonean Leone", "symbol": "SLL"},
{"name": "Somali Shilling", "symbol": "SOS"},
{"name": "Surinamese Dollar", "symbol": "SRD"},
{"name": "Surinamese Guilder", "symbol": "SRG"},
{"name": "South Sudanese Pound", "symbol": "SSP"},
{"name": "São Tomé & Príncipe Dobra", "symbol": "STD"},
{"name": "Soviet Rouble", "symbol": "SUR"},
{"name": "Salvadoran Colón", "symbol": "SVC"},
{"name": "Syrian Pound", "symbol": "SYP"},
{"name": "Swazi Lilangeni", "symbol": "SZL"},
{"name": "Thai Baht", "symbol": "THB"},
{"name": "Tajikistani Ruble", "symbol": "TJR"},
{"name": "Tajikistani Somoni", "symbol": "TJS"},
{"name": "Turkmenistani Manat (1993–2009)", "symbol": "TMM"},
{"name": "Turkmenistani Manat", "symbol": "TMT"},
{"name": "Tunisian Dinar", "symbol": "TND"},
{"name": "Tongan Paʻanga", "symbol": "TOP"},
{"name": "Timorese Escudo", "symbol": "TPE"},
{"name": "Turkish Lira (1922–2005)", "symbol": "TRL"},
{"name": "Turkish Lira", "symbol": "TRY"},
{"name": "Trinidad & Tobago Dollar", "symbol": "TTD"},
{"name": "New Taiwan Dollar", "symbol": "NT$"},
{"name": "Tanzanian Shilling", "symbol": "TZS"},
{"name": "Ukrainian Hryvnia", "symbol": "UAH"},
{"name": "Ukrainian Karbovanets", "symbol": "UAK"},
{"name": "Ugandan Shilling (1966–1987)", "symbol": "UGS"},
{"name": "Ugandan Shilling", "symbol": "UGX"},
{"name": "US Dollar", "symbol": "USD"},
{"name": "US Dollar (Next day)", "symbol": "USN"},
{"name": "US Dollar (Same day)", "symbol": "USS"},
{"name": "Uruguayan Peso (Indexed Units)", "symbol": "UYI"},
{"name": "Uruguayan Peso (1975–1993)", "symbol": "UYP"},
{"name": "Uruguayan Peso", "symbol": "UYU"},
{"name": "Uzbekistan Som", "symbol": "UZS"},
{"name": "Venezuelan Bolívar (1871–2008)", "symbol": "VEB"},
{"name": "Venezuelan Bolívar", "symbol": "VEF"},
{"name": "Vietnamese Dong", "symbol": "₫"},
{"name": "Vietnamese Dong (1978–1985)", "symbol": "VNN"},
{"name": "Vanuatu Vatu", "symbol": "VUV"},
{"name": "Samoan Tala", "symbol": "WST"},
{"name": "CFA Franc BEAC", "symbol": "FCFA"},
{"name": "Silver", "symbol": "XAG"},
{"name": "Gold", "symbol": "XAU"},
{"name": "European Composite Unit", "symbol": "XBA"},
{"name": "European Monetary Unit", "symbol": "XBB"},
{"name": "European Unit of Account (XBC)", "symbol": "XBC"},
{"name": "European Unit of Account (XBD)", "symbol": "XBD"},
{"name": "East Caribbean Dollar", "symbol": "EC$"},
{"name": "Special Drawing Rights", "symbol": "XDR"},
{"name": "European Currency Unit", "symbol": "XEU"},
{"name": "French Gold Franc", "symbol": "XFO"},
{"name": "French UIC-Franc", "symbol": "XFU"},
{"name": "CFA Franc BCEAO", "symbol": "CFA"},
{"name": "Palladium", "symbol": "XPD"},
{"name": "CFP Franc", "symbol": "CFPF"},
{"name": "Platinum", "symbol": "XPT"},
{"name": "RINET Funds", "symbol": "XRE"},
{"name": "Sucre", "symbol": "XSU"},
{"name": "Testing Currency Code", "symbol": "XTS"},
{"name": "ADB Unit of Account", "symbol": "XUA"},
{"name": "Yemeni Dinar", "symbol": "YDD"},
{"name": "Yemeni Rial", "symbol": "YER"},
{"name": "Yugoslavian Hard Dinar (1966–1990)", "symbol": "YUD"},
{"name": "Yugoslavian New Dinar (1994–2002)", "symbol": "YUM"},
{"name": "Yugoslavian Convertible Dinar (1990–1992)", "symbol": "YUN"},
{"name": "Yugoslavian Reformed Dinar (1992–1993)", "symbol": "YUR"},
{"name": "South African Rand (financial)", "symbol": "ZAL"},
{"name": "South African Rand", "symbol": "ZAR"},
{"name": "Zambian Kwacha (1968–2012)", "symbol": "ZMK"},
{"name": "Zambian Kwacha", "symbol": "ZMW"},
{"name": "Zairean New Zaire (1993–1998)", "symbol": "ZRN"},
{"name": "Zairean Zaire (1971–1993)", "symbol": "ZRZ"},
{"name": "Zimbabwean Dollar (1980–2008)", "symbol": "ZWD"},
{"name": "Zimbabwean Dollar (2009)", "symbol": "ZWL"},
{"name": "Zimbabwean Dollar (2008)", "symbol": "ZWR"}
]

